# Generated by Django 3.0.8 on 2020-07-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0005_auto_20200714_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='company',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
