# Generated by Django 3.0.8 on 2020-07-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0007_auto_20200715_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspaper',
            name='lang',
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='language',
            field=models.CharField(choices=[('Tamil', 'Tamil'), ('English', 'English'), ('Sinhala', 'Sinhala')], max_length=50),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='publication',
            field=models.CharField(choices=[('Weekdays', 'Weekdays'), ('Weekend', 'Weekend')], max_length=50),
        ),
    ]
