# Generated by Django 3.0.8 on 2020-07-14 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0009_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewspaperAPI.Newspaper'),
        ),
    ]
