# Generated by Django 3.0.8 on 2020-07-14 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0010_auto_20200715_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='newspaper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NewspaperAPI.Newspaper'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewspaperAPI.Consumer'),
        ),
    ]
