# Generated by Django 3.0.8 on 2020-07-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0011_auto_20200715_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='newspaper',
        ),
        migrations.AddField(
            model_name='order',
            name='newspaper',
            field=models.ManyToManyField(to='NewspaperAPI.Newspaper'),
        ),
    ]
