# Generated by Django 3.0.8 on 2020-07-15 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0012_auto_20200715_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='newspaper',
        ),
        migrations.AddField(
            model_name='order',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
