# Generated by Django 3.0.8 on 2020-07-15 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0015_auto_20200715_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='add_date',
            new_name='Create_date',
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NewspaperAPI.Consumer'),
            preserve_default=False,
        ),
    ]
