# Generated by Django 3.0.8 on 2020-07-15 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0017_auto_20200715_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='newspaper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NewspaperAPI.Newspaper'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, max_length=32),
        ),
    ]
