# Generated by Django 3.0.8 on 2020-07-15 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0019_auto_20200715_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='newspaper',
            new_name='Newspaper',
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, max_length=32)),
                ('qty', models.IntegerField(default=0)),
                ('qty_return', models.IntegerField(default=0)),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewspaperAPI.Newspaper')),
            ],
        ),
    ]
