# Generated by Django 3.0.8 on 2020-07-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0020_auto_20200715_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspaper',
            old_name='price',
            new_name='re_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Newspaper',
            new_name='newspaper',
        ),
        migrations.AddField(
            model_name='newspaper',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
