# Generated by Django 3.0.8 on 2020-07-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0022_auto_20200716_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='intake',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
