# Generated by Django 3.0.8 on 2020-07-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0023_intake_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivary',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
