# Generated by Django 3.0.8 on 2020-07-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0024_order_delivary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='newspaper',
            new_name='newspapers',
        ),
    ]
