# Generated by Django 3.0.8 on 2020-07-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0025_auto_20200721_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='newspapers',
            new_name='newspaper',
        ),
    ]
