# Generated by Django 3.0.8 on 2020-07-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0027_consumer_ac_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('subtitle', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=40)),
                ('contact1', models.CharField(max_length=15)),
                ('contact2', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
    ]
