# Generated by Django 3.0.8 on 2020-07-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0028_regi'),
    ]

    operations = [
        migrations.AddField(
            model_name='regi',
            name='co_re_no',
            field=models.CharField(default=21, max_length=20),
            preserve_default=False,
        ),
    ]
