# Generated by Django 3.0.8 on 2020-07-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0029_regi_co_re_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='added_date',
            field=models.DateField(max_length=32),
        ),
    ]
