# Generated by Django 3.0.8 on 2020-07-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0030_auto_20200730_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='added_date',
            field=models.DateField(auto_now_add=True, max_length=32),
        ),
    ]
