# Generated by Django 3.0.8 on 2020-07-31 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0033_daily_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newspaper_Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.IntegerField(default=0)),
                ('note', models.CharField(max_length=32)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('due_payment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('statues', models.CharField(choices=[('Paid', 'Paid'), ('Not_Paid', 'Not_Paid')], max_length=50)),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewspaperAPI.Intake')),
            ],
        ),
    ]
