# Generated by Django 3.0.8 on 2020-07-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0034_newspaper_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspaper_payment',
            old_name='Qty',
            new_name='qty',
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='publication',
            field=models.CharField(choices=[('Weekdays', 'Weekdays'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=50),
        ),
    ]
