# Generated by Django 3.0.8 on 2020-07-31 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0035_auto_20200731_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='newspaper',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='NewspaperAPI.Newspaper'),
        ),
    ]
