# Generated by Django 3.0.8 on 2020-08-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0037_auto_20200801_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspaper',
            old_name='name',
            new_name='newspaper',
        ),
        migrations.AlterField(
            model_name='intake',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
