# Generated by Django 3.0.8 on 2020-08-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0038_auto_20200804_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
