# Generated by Django 3.0.8 on 2020-08-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0040_auto_20200806_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='total',
            field=models.IntegerField(),
        ),
    ]
