# Generated by Django 3.0.8 on 2020-08-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewspaperAPI', '0041_auto_20200806_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
